### ISSUE TITLE
IndexError while generating plot

### ISSUE THREAD

**Issue by SteveJos** [ccampo133/Plot-Pings-in-Python#13]
Hey @ccampo133, great tool! But when it comes to a host that has a lot of downtime the script does not generate plot data and crashs with the following error:

```
Press CTRL+C to quit...

   AVG. PING      PACKET LOSS     NUM. PINGS     NUM. TIMEOUTS   TIME ELAPSED

    8.67 ms         93.27 %          1665            1553           1:36:32    ^C

Traceback (most recent call last):
  File "pingplot.py", line 206, in <module>
    sys.exit(main())
  File "pingplot.py", line 191, in main
    plt = plot_gen(ping, now, nans, opts.host, opts.plot, opts.size)
  File "pingplot.py", line 85, in plot_gen
    if i != len(nans) and nans[i + 1] != nans[i]:
IndexError: index 1665 is out of bounds for axis 0 with size 1665
```

I hope that you could fix that :)

Cheers

**Comment by ccampo133** [comment]
Fixed in https://github.com/ccampo133/Plot-Pings-in-Python/pull/14
